export const ADD_MEMORIES = 'ADD_MEMORIES';
export const ADD_MEMORY = 'ADD_MEMORY';
export const REMOVE_MEMORY = 'REMOVE_MEMORY';
export const POPULATE_FROM_API = 'POPULATE_FROM_API';

export const FETCHING_REPOS = 'FETCHING_REPOS';
export const REPOS_FETCH_SUCCESS = 'REPOS_FETCH_SUCCESS';
